version: '3.2'

services: 
    spider:
        image: mariadb:10.1
        container_name: spider
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: ssu
        ports: 
            - 3306:3306
        volumes:
            - ./shard-data/spider/data:/var/lib/mysql
            - ../employees_db:/data-set
        networks:
            static-network:
                ipv4_address: 172.20.0.2
    shard1:
        image: mariadb:10.1
        container_name: shard1
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: ssu
        ports: 
            - 3307:3306
        volumes:
            - ./shard-data/shard1/data:/var/lib/mysql
        depends_on:
            - spider
        networks:
            static-network:
                ipv4_address: 172.20.0.3
    shard2:
        image: mariadb:10.1
        container_name: shard2
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: ssu
        ports: 
            - 3308:3306
        volumes:
            - ./shard-data/shard2/data:/var/lib/mysql
        depends_on:
            - spider
        networks:
            static-network:
                ipv4_address: 172.20.0.4
networks:
    static-network:
        ipam:
            config:
                - subnet: 172.20.0.0/16
