version: '3.2'

services: 
    master:
        image: mysql:5.6
        container_name: master
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: ssu
        ports: 
            - 3306:3306
        volumes:
            - ./repl-data/master/data:/var/lib/mysql
            - ./repl-data/master/conf:/etc/mysql/conf.d
            - ../../employees_db:/data-set
        networks:
            static-network:
                ipv4_address: 172.20.0.2
    slave1:
        image: mysql:5.6
        container_name: slave1
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: ssu
        ports: 
            - 3307:3306
        volumes:
            - ./repl-data/slave1/data:/var/lib/mysql
            - ./repl-data/slave1/conf:/etc/mysql/conf.d
        depends_on:
            - master
        networks:
            static-network:
                ipv4_address: 172.20.0.3
    slave2:
        image: mysql:5.6
        container_name: slave2
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: ssu
        ports: 
            - 3308:3306
        volumes:
            - ./repl-data/slave2/data:/var/lib/mysql
            - ./repl-data/slave2/conf:/etc/mysql/conf.d
        depends_on:
            - master
        networks:
            static-network:
                ipv4_address: 172.20.0.4
networks:
    static-network:
        ipam:
            config:
                - subnet: 172.20.0.0/16
