version: '3.2'

services: 
    mysql-master:
        image: mysql:5.6
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: ssu
        ports: 
            - 3306:3306
        volumes:
            - ./mysql-repl/master/data:/var/lib/mysql
            - ./mysql-repl/master/conf:/etc/mysql/conf.d
            - ./mysql-repl/source-set:/source-set
        networks:
            static-network:
                ipv4_address: 172.20.0.2
    mysql-slave1:
        image: mysql:5.6
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: ssu
        ports: 
            - 3307:3306
        volumes:
            - ./mysql-repl/slave1/data:/var/lib/mysql
            - ./mysql-repl/slave1/conf:/etc/mysql/conf.d
        depends_on:
            - mysql-master
    mysql-slave2:
        image: mysql:5.6
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: ssu
        ports: 
            - 3308:3306
        volumes:
            - ./mysql-repl/slave2/data:/var/lib/mysql
            - ./mysql-repl/slave2/conf:/etc/mysql/conf.d
        depends_on:
            - mysql-master
networks:
    static-network:
        ipam:
            config:
                - subnet: 172.20.0.0/16
